---
- hosts: base_image
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Install Apache, PHP and Git.
      yum: 
        name:
          - httpd
          - php
          - git
        state: present
    - name: Download website src from Git
      git:
        repo: https://github.com/samieyjay/checkout-web.git
        dest: /var/www/html
    - name: Change www directory ownership
      file:
        path: /var/www/html/
        mode: 0755
        recurse: yes
        owner: apache
        group: apache
    - name: Start Apache at boot.
      service: name=httpd state=started enabled=yes
